---
title: "ds4biomed"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: false
runtime: shiny_prerendered
---

```{r, include=FALSE, child="../010-setup.Rmd"}
```

```{r,  child="../020-010-pre_workshop_exercise.Rmd"}
```

## Exercise 1

```{r,  child="../030-005-exercise_1_setup.Rmd"}
```

```{r,  child="../030-010-exercise_1_prompt.Rmd"}
```

```{r,  child="../030-040-exercise_1_gradethis.Rmd"}
# contains ex1-solution chunk
# contains ex1-code-check chunk
```

```{r,  child="../030-020-exercise_1_blank.Rmd"}
# contains ex1 chunk
```

## Exercise 2

```{r, child="../040-010-exercise_2_setup.Rmd"}
```

```{r, child="../040-020-exercise_2_prompt.Rmd"}
```

```{r, child="../040-050-exercise_2_gradethis.Rmd"}
# contains ex2-solution chunk
# contains ex2-code-check chunk
```

```{r, child="../040-030-exercise_2_blank.Rmd"}
# contains ex2 chunk
```

## Exercise 3

```{r, child="../050-010-exercise_3_setup.Rmd"}
```

```{r, child="../050-020-exercise_3_prompt.Rmd"}
```

```{r, child="../050-050-exercise_3_gradethis.Rmd"}
# contains ex3-solution chunk
# contains ex3-code-check chunk
```

```{r, child="../050-030-exercise_3_blank.Rmd"}
# contains ex3 chunk
```

## Summative

```{r, child="../060-010-exercise_summ_prompt.Rmd"}
```
